# Generated by Django 5.1.5 on 2025-01-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('query_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
