# Generated by Django 5.1.5 on 2025-01-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionquery',
            name='query_date',
        ),
        migrations.AlterField(
            model_name='transactionquery',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
